# Generated by Django 4.1 on 2024-02-04 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crendential', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crendential',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_document', to=settings.AUTH_USER_MODEL),
        ),
    ]
