# Generated by Django 4.1 on 2024-02-04 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
        ('crendential', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crendential',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='crendentials', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='crendential',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
