# Generated by Django 4.1 on 2024-03-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crendential', '0002_alter_crendential_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='crendential',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='crendential',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
