# Generated by Django 4.1 on 2024-03-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsuser',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'STUDENT'), ('INSTRUCTOR', 'INSTRUCTOR')], default='PDF', max_length=255, verbose_name='Role'),
        ),
    ]
