# Generated by Django 5.0.1 on 2024-01-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='intro_video',
            field=models.URLField(default='https://youtu.be/S-rOWaiKPgk'),
        ),
    ]
