# Generated by Django 4.1 on 2023-06-01 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursecategory_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['title'], 'verbose_name': 'Course'},
        ),
    ]
