# Generated by Django 4.1 on 2023-06-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_subject_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='slug',
            field=models.SlugField(default=2, unique=True),
            preserve_default=False,
        ),
    ]
