# Generated by Django 4.1 on 2024-01-02 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_coursecategory_delete_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sub_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='courses.coursecategory', verbose_name='Sub Category'),
        ),
    ]
