# Generated by Django 4.1 on 2024-01-04 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='category',
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Course Name '),
            preserve_default=False,
        ),
    ]
