# Generated by Django 5.0.1 on 2024-01-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_category_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='pdfs',
            field=models.ManyToManyField(blank=True, to='courses.file'),
        ),
    ]
