# Generated by Django 4.1 on 2024-02-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multichoice', '0002_alter_answer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(blank=True, default=True, help_text='Is this a correct answer?', verbose_name='Correct'),
        ),
    ]
