# Generated by Django 4.1 on 2024-02-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multichoice', '0003_alter_answer_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(blank=True, default=False, help_text='Is this a correct answer?', verbose_name='Correct'),
        ),
    ]
