# Generated by Django 4.1 on 2024-02-12 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_quiz_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_questions',
            field=models.ManyToManyField(related_name='question_quiz', to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_question', to='quiz.quiz', verbose_name='Quiz'),
        ),
    ]
