# Generated by Django 4.1 on 2024-02-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_quiz_questions_alter_sitting_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_questions',
        ),
    ]
